# Project: GoLtest
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = ../algorithm.o ../sdlevents.o unitTestsGameOfLife.o unity.o
LINKOBJ  = ../algorithm.o ../sdlevents.o unitTestsGameOfLife.o unity.o
LIBS     = -L"D:/CS/Dev-Cpp/TDM-GCC-64/lib" -L"D:/CS/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -lmingw32 -lSDL2main -lSDL2 -g3
INCS     = -I"D:/CS/Dev-Cpp/TDM-GCC-64/include" -I"D:/CS/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/CS/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/CS/Dev-Cpp/TDM-GCC-64/include" -I"D:/CS/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/CS/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/CS/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = GoLtest.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
DEL      = D:\CS\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

../algorithm.o: ../algorithm.c
	$(CC) -c ../algorithm.c -o ../algorithm.o $(CFLAGS)

../sdlevents.o: ../sdlevents.c
	$(CC) -c ../sdlevents.c -o ../sdlevents.o $(CFLAGS)

unitTestsGameOfLife.o: unitTestsGameOfLife.c
	$(CC) -c unitTestsGameOfLife.c -o unitTestsGameOfLife.o $(CFLAGS)

unity.o: unity.c
	$(CC) -c unity.c -o unity.o $(CFLAGS)
